### ISSUE TITLE
fails when running production build npm run build

### ISSUE THREAD

**Issue by uthpalax** [blakek/geo2zip#15]
This is the error message i am getting 

SyntaxError: Name expected [./~/geo2zip/index.js:2,0]

**Comment by blakek** [comment]
@Uthpala, can you show me an example of how you're using this?  Also, this is currently tageting Node.js LTS; are you trying to use it in a browser?  If not, could you tell me what environment you're targeting?

Thanks!

**Comment by blakek** [comment]
Assuming this is resolved.  If you have any other issues, feel free to comment.

**Comment by gdevany** [comment]
I am using geo2zip and getting the same error during compile while trying to deploy my app to Heroku using `npm run pre-deploy`.  I am just a student learning React (with Redux, Express), so forgive me for any ignorance.  BTW- everything works great in development.  Here's a link to my github for this project: https://github.com/gdevany/advanced-heroku-app

**Comment by blakek** [comment]
@gdevany The reason is probably that this library isn't being transpiled—it's only meant to run on a Node.js server right now.

If you're interested, it should be trivial to make this work in a browser.  The main reason I haven't already done that is it means roughly 1.5mb will be sent to the client's browser.

What I'd suggest doing is moving this library to your server code.  Then have your client code make an AJAX call to that new endpoint.

**Comment by gdevany** [comment]
Thanks for the quick response.  I'll try moving it to server code.
